name: Debug
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - "*"
jobs:
  prints:
    strategy:
      matrix:
        vars:
        - ${{ github.repository_owner_id }}
        - ${{ github.run_id }}
        - ${{ github.action }}
    runs-on: "ubuntu-latest"
    steps:
    - name: Printall
      run: |
        echo ${{ matrix.vars }}
        ehco $GITHUB_ACTION
